steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'USER_NAME=${_USER_NAME}'
    - 'PASSWORD=${_PASSWORD}'
    - 'DATABASE=${_DATABASE}'
    - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
    - 'ACCESS_TOKEN=${_ACCESS_TOKEN}'
    - 'APP_ID=${_APP_ID}'
    - 'APP_SECRET=${_APP_SECRET}'
    - 'VERIFY_TOKEN=${_VERIFY_TOKEN}'
    - 'HASH_IV=${_HASH_IV}'
    - 'HASH_KEY=${_HASH_KEY}'
    - 'MERCHANT_ID=${_MERCHANT_ID}'
    - 'IMGUR_CLIENT_ID=&{_IMGUR_CLIENT_ID}'
    - 'GCS_BUCKET=&{_GCS_BUCKET}'
    - 'GCLOUD_PROJECT=&{_GCLOUD_PROJECT}'
    - 'GCS_KEYFILE=&{_GCS_KEYFILE}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"